blog/urls.py
from django.urls import path,include
from .views import *
from comment.views import index as index_comment
import comment.urls as comment

urlpatterns = [
    path('', index, name = 'index'),
    path('add/', add_forum, name='add'),
   
    path('<int:id>', index_comment, name='comment'),
    path('comment/',include(comment)),
]

haddadblog/urls.py
from django.contrib import admin
from django.urls import include, path
import blog.urls as blog
import register.urls as register


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('articles/',include(blog)),
    path('register/',include(register)),
    path('register/', include('django.contrib.auth.urls')),
    
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="haddadblog merupakan personal blogging berisi profil dan artikel milik haddad">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="icon" href="{% static 'img/haddadblog.png' %}" type="image/x-icon">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div id="loader-container">
    <div id="loader">Loading...</div>
  </div>
  <div id="root">
    {% include 'navbar.html' %}

    <main>
      {% if messages %}
      {% for message in messages %}

      <div id="notify" notifyType="{{message.tags}}" notifyMessage="{{message}}">
      </div>

      {% endfor %}
      {% endif %}


      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@reliutg/buzz-notify/index.min.js"></script>
  <script src="{% static 'js/script.js' %}"></script>

  {% block js %}
  {% endblock js %}
</body>

</html>

templates/base2.html
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>haddadblog</title>

    <head>
        <link rel="stylesheet" href={% static 'css/style.css' %}>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
</head>
{% block body %}


<body>
    <div class="hero">

       


        {% block content %}
        {% endblock content %}
        
    </div>
</body>


{% endblock body %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>

templates/baseBackup.html
{%load static%}
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>haddadblog</title>

    <head>
        <link rel="stylesheet" href={% static 'css/style.css' %}>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block meta %}

        {% endblock meta %}
    </head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
</head>



<body>
    <div class="hero">
        <nav class="navbar navbar-expand-lg navbar-dark bg-inverse">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">haddadblog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="">Experiences</a>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Blog
                </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="/articles">Read articles</a></li>
                                <li><a class="dropdown-item" href="#">Sign up</a></li>


                            </ul>
                        </li>

                    </ul>
                    {% if not user.is_authenticated %}



                    <a href="../register/login">
                        <button type="button" class="btn btn-primary">Login</button>
                    </a>
                    <a href="../register">
                        <button type="button" class="btn btn-success">Signup</button>
                    </a>


                    {% else %}

                    <a href="../register/logout">
                        <button type="button" class="btn btn-danger">Logout</button>
                    </a>


                    {% endif %}


                </div>

            </div>
        </nav>


        {% block body %}
        {% endblock body %}
</body>

{% block js %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% endblock js %}
</html>

templates/navbar.html
{%load static%}
<nav class="navbar navbar-expand-lg navbar-dark bg-inverse">
  <div class="container-fluid container">
    {% comment %} <img src="" style="width: 6% ; padding: 10px; " alt="invid19"> {% endcomment %}
    <a class="navbar-brand" href="#">haddadblog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-lg-row justify-content-between" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles">Artikel</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href=""></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href=""></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""></a>
        </li>
       
      </ul>
      {% if request.user.is_authenticated %}
      <a href="{% url 'logout' %}">
        <button type="button" class="btn btn-danger">Logout</button>
      </a>
      {% else %}
      {% if request.path == 'register/login' %}
      <a href="">
        <button type="button" class="btn btn-success">Signup</button>
      </a>
      {% else %}
      <a href="{% url 'login' %}">
        <button type="button" class="btn btn-success">Login</button>
      </a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</nav>